### ISSUE TITLE
When does the update of the discrete action parameters happen?

### ISSUE THREAD

**Issue by sasforce** [cycraig/MP-DQN#2]
When does the update of the the discrete action parameters happen? There is no usage of '_action_update'  function in 'learn' function of the file 'qpamdp.py'. 
Thank you.

**Comment by cycraig** [comment]
Hi, the Q-PAMDP class encapsulates a discrete action agent to which it delegates discrete action learning, in this case using Sarsa(λ). This agent is updated in the `_rollout` function of `qpamdp.py`, where the `step` function of the discrete agent is called.

**Comment by sasforce** [comment]
Thank you！
